version: '3'
services:
  mariadb-test:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=wp-database 
      - MARIADB_USER=wp-user 
      - MARIADB_PASSWORD=1234 
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - mariadb-volume:/var/lib/mysql
  wordpress-test:
    image: wordpress
    ports: 
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=192.168.15.181
      - WORDPRESS_DB_USER=wp-user 
      - WORDPRESS_DB_NAME=wp-database 
      - WORDPRESS_DB_PASSWORD=1234 
      - WORDPRESS_TABLE_PREFIX=testwp_
    volumes:
      - wordpress-volume:/var/www/html/wp-content
volumes:
  wordpress-volume:
    driver: local
  mariadb-volume:
    driver: local
