version: '3'
services:
  mariadb-test:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=<dbname_here>
      - MARIADB_USER=<username_here>
      - MARIADB_PASSWORD=<password_here>
      - MARIADB_ROOT_PASSWORD=<password_here>
    volumes:
      - mariadb-volume:/var/lib/mysql
  wordpress-test:
    image: wordpress
    ports: 
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=<host>
      - WORDPRESS_DB_USER=<username>
      - WORDPRESS_DB_NAME=<dbname>
      - WORDPRESS_DB_PASSWORD=<password>
      - WORDPRESS_TABLE_PREFIX=<tableprefix>
    volumes:
      - wordpress-volume:/var/www/html/wp-content
volumes:
  wordpress-volume:
    driver: local
  mariadb-volume:
    driver: local
